apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 1.9.0
  syncPolicy:
    automated:
      selfHeal: true